version: "3"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    #network_mode: host
    restart: always
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=1000
      - PUID=1000
      - CF_API_TOKEN=YOUR-CLOUDFLARE-API-TOKEN # pls adjust
      - DOMAINS=example.org,www.example.org,example.io # pls adjust; a list of fully qualified domain names separated by commas
      - PROXIED=false # instructs Cloudflare to cache webpages on your machine and hide its actual IP addresses
      - TZ=Europe/Berlin
      - IP6_PROVIDER=none # disbale IPv6
