version: '3.4'
services:
  bibliogram:
    image: schklom/bibliogram
    container_name: bibliogram
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/bibliogram/config.js:/app/config.js:ro
    ports:
      - 10407:10407
    restart: unless-stopped
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.bibliogram.rule=Host(`bibliogram.example.com`)
    #  - traefik.http.services.bibliogram.loadbalancer.server.port=10407
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.bibliogram.middlewares=local-ipwhitelist@file,authelia@docker

#networks:
#  proxy:
#    external: true  
